name: Run unit tests

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

jobs:
    test:
        name: Run unit tests
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Install dependencies
              run: pip install -r requirements.txt
            - name: Test
              run: |
                cd src
                python -m unittest
